### ISSUE TITLE
Can't install in Sublime Text 3

### ISSUE THREAD

**Issue by revolter** [sublime-ycmd/sublime-ycmd#1]
Searching for `YouCompleteMe` doesn't return this package.

**Comment by FichteFoll** [comment]
The package only defines pre-releases on its [tags page](https://github.com/sublime-ycmd/sublime-ycmd/tags) (indicated by `-beta.2`). Package Control only installs pre-releases if a user has configured it to do so for certain packages.

@OmgLag you should push a non-pre-release tag so that users can actually install the package.

**Comment by revolter** [comment]
Maybe it is intended as a pre-release, as it's only a couple of months old. Couldn't packagecontrol.io mention that it was not yet released and how can you install it?

**Comment by akshayganeshen** [comment]
This is indeed a pre-release. A proper release is coming in a few days. Sorry for the wait!

**Comment by revolter** [comment]
Do you plan to release a comparison between this and https://github.com/LuckyGeck/YcmdCompletion?

**Comment by FichteFoll** [comment]
@revolter It could, probably. Currently it looks like version aggregation for the latest version to be displayed isn't working for pre-release-only packages, as there is no version listed on the PC page.
An idea might be to add a link to the [relevant setting](https://packagecontrol.io/docs/settings#setting-install_prereleases) on the "PRE" tag that can be seen on package listings like [SublimeLinter's](https://packagecontrol.io/packages/SublimeLinter).

![2018-01-14_19-16-27](https://user-images.githubusercontent.com/931051/34919183-8716be5c-f95f-11e7-98f0-2ba1515e6a21.png)
![2018-01-14_19-16-39](https://user-images.githubusercontent.com/931051/34919184-8735117c-f95f-11e7-874d-b75af1b44b0b.png)


You can create an issue on https://github.com/wbond/packagecontrol.io/ for it.

**Comment by akshayganeshen** [comment]
@revolter The README will indeed be updated with a comparison once the release is out.

**Comment by revolter** [comment]
@OmgLag, Thank you for the info!
